name: Build workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: registry.hub.docker.com/arunkumar9t2/scabbard:latest
    steps:
      - uses: actions/checkout@v1

      - name: Set gradle permissions
        run: |
          sudo chmod +x ./gradlew
          cd scabbard-gradle-plugin
          sudo chmod +x ./gradlew

      - name: Build scabbard project
        run: |
          ./gradlew assemble

      - name: Build scabbard gradle plugin
        run: |
          cd scabbard-gradle-plugin
          ./gradlew assemble

      - name: Test scabbard project
        run: |
          ./gradlew check

      - name: Test scabbard gradle plugin
        run: |
          cd scabbard-gradle-plugin
          ./gradlew check
