name: Build Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set gradle permissions
        run: sudo chmod +x ./gradlew
      - name: Download dependencies
        run: |
          ./gradlew dependencies

      - name: Build project
        run: |
          ./gradlew assemble

      - name: Test project
        run: |
          ./gradlew check