name: Build workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install GraphViz
        run: sudo apt-get install graphviz

      - name: Set gradle permissions
        run: sudo chmod +x ./gradlew
      - name: Download dependencies
        run: |
          ./gradlew dependencies

      - name: Build scabbard project
        run: |
          ./gradlew assemble

      - name: Build scabbard gradle plugin
        run: |
          cd scabbard-gradle-plugin
          ./gradlew assemble

      - name: Test scabbard project
        run: |
          ./gradlew check

      - name: Test scabbard gradle plugin
        run: |
          cd scabbard-gradle-plugin
          ./gradlew check