name: Publish docs workflow

on:
  push:
    branches:
      - main
    paths:
      - 'docs/*'
      - 'mkdocs.yml'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install MkDocs
        run: |
          pip install -Iv mkdocs==1.2.1
          pip install -Iv mkdocs-material==7.1.8

      - name: Setup git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Setting up git"
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote rm origin
          git remote add origin https://x-access-token:$GITHUB_TOKEN@github.com/${{ github.repository }}.git

      - name: Publish to gh-pages
        run: mkdocs gh-deploy -v --config-file "${GITHUB_WORKSPACE}/mkdocs.yml" --force